using Microsoft.EntityFrameworkCore;
using Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();
builder.Services.AddDbContext<VocationalDbContext>(options =>
{
    var conn = builder.Configuration.GetConnectionString("DefaultConnection");
    options.UseNpgsql(conn ?? "Host=localhost;Database=postgres;Username=postgres;Password=postgres");
});

var app = builder.Build();

// Ensure database is created with seed data
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<VocationalDbContext>();
    db.Database.EnsureCreated();
    
    // Force create missing tables if EnsureCreated skipped them due to partial creation
    try 
    {
        db.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""Sesiones"" (
                ""Id"" uuid NOT NULL,
                ""FechaCreacion"" timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_Sesiones"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""Respuestas"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""SesionId"" uuid NOT NULL,
                ""ActividadId"" integer NOT NULL,
                ""MeInteresa"" boolean NOT NULL,
                CONSTRAINT ""PK_Respuestas"" PRIMARY KEY (""Id""),
                CONSTRAINT ""FK_Respuestas_Actividades_ActividadId"" FOREIGN KEY (""ActividadId"") REFERENCES ""Actividades"" (""Id"") ON DELETE CASCADE,
                CONSTRAINT ""FK_Respuestas_Sesiones_SesionId"" FOREIGN KEY (""SesionId"") REFERENCES ""Sesiones"" (""Id"") ON DELETE CASCADE
            );
        ");
    }
    catch (Exception ex)
    {
        Console.WriteLine("Error forcing table creation: " + ex.Message);
    }
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseRouting();

app.UseAuthorization();

app.MapStaticAssets();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Test}/{action=Start}/{id?}")
    .WithStaticAssets();


app.Run();
